#!/bin/bash

# dummy script for flashing

echo "sme v lattice"

while [ $# -gt 0 ]
do
    if [ "$1" = "-logfile" ]
    then
        INFILE="$2"
        break
    fi
    shift
done
if [ "$INFILE" ]
then
    echo "Operation: successful." > "$INFILE"
else
    echo "missing logfile"
fi

sleep 2
