# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/programmer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Programmer(object):
    def setupUi(self, Programmer):
        Programmer.setObjectName("Programmer")
        Programmer.resize(656, 558)
        Programmer.setFrameShape(QtWidgets.QFrame.Box)
        Programmer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalLayout = QtWidgets.QVBoxLayout(Programmer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.indexLabel = QtWidgets.QLabel(Programmer)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.indexLabel.setFont(font)
        self.indexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.indexLabel.setObjectName("indexLabel")
        self.verticalLayout.addWidget(self.indexLabel)
        self.contentWidget = QtWidgets.QStackedWidget(Programmer)
        self.contentWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentWidget.setObjectName("contentWidget")
        self.pageIntro = QtWidgets.QWidget()
        self.pageIntro.setObjectName("pageIntro")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageIntro)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.pageIntro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 300))
        self.label.setMaximumSize(QtCore.QSize(300, 300))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/favicon-big.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.introWidget = QtWidgets.QStackedWidget(self.pageIntro)
        self.introWidget.setObjectName("introWidget")
        self.pageIntroConnect = QtWidgets.QWidget()
        self.pageIntroConnect.setObjectName("pageIntroConnect")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageIntroConnect)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.pageIntroConnect)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.pageIntroConnect)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.introWidget.addWidget(self.pageIntroConnect)
        self.pageIntroReady = QtWidgets.QWidget()
        self.pageIntroReady.setObjectName("pageIntroReady")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageIntroReady)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.introMessageLabel = QtWidgets.QLabel(self.pageIntroReady)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.introMessageLabel.setFont(font)
        self.introMessageLabel.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.introMessageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.introMessageLabel.setObjectName("introMessageLabel")
        self.verticalLayout_7.addWidget(self.introMessageLabel)
        self.introErrorLabel = QtWidgets.QLabel(self.pageIntroReady)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.introErrorLabel.setFont(font)
        self.introErrorLabel.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.introErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.introErrorLabel.setObjectName("introErrorLabel")
        self.verticalLayout_7.addWidget(self.introErrorLabel)
        self.introWidget.addWidget(self.pageIntroReady)
        self.pageIntroSerial = QtWidgets.QWidget()
        self.pageIntroSerial.setObjectName("pageIntroSerial")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageIntroSerial)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.scanBoardLabel = QtWidgets.QLabel(self.pageIntroSerial)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.scanBoardLabel.setFont(font)
        self.scanBoardLabel.setObjectName("scanBoardLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.scanBoardLabel)
        self.barcodeLineEdit = QtWidgets.QLineEdit(self.pageIntroSerial)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.barcodeLineEdit.setFont(font)
        self.barcodeLineEdit.setObjectName("barcodeLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.barcodeLineEdit)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.introWidget.addWidget(self.pageIntroSerial)
        self.verticalLayout_3.addWidget(self.introWidget)
        self.contentWidget.addWidget(self.pageIntro)
        self.pageWork = QtWidgets.QWidget()
        self.pageWork.setObjectName("pageWork")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageWork)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.typeLabel = QtWidgets.QLabel(self.pageWork)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.typeLabel.setFont(font)
        self.typeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.typeLabel.setObjectName("typeLabel")
        self.horizontalLayout_2.addWidget(self.typeLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.pageWork)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.serialNumberLabel = QtWidgets.QLabel(self.pageWork)
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(20)
        self.serialNumberLabel.setFont(font)
        self.serialNumberLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.serialNumberLabel.setObjectName("serialNumberLabel")
        self.verticalLayout_5.addWidget(self.serialNumberLabel)
        self.scrollArea = QtWidgets.QScrollArea(self.pageWork)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 614, 347))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(20, 291, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.currentProgress = QtWidgets.QProgressBar(self.pageWork)
        self.currentProgress.setMaximum(100)
        self.currentProgress.setProperty("value", 0)
        self.currentProgress.setObjectName("currentProgress")
        self.verticalLayout_5.addWidget(self.currentProgress)
        self.totalProgress = QtWidgets.QProgressBar(self.pageWork)
        self.totalProgress.setMaximum(0)
        self.totalProgress.setProperty("value", 0)
        self.totalProgress.setObjectName("totalProgress")
        self.verticalLayout_5.addWidget(self.totalProgress)
        self.contentWidget.addWidget(self.pageWork)
        self.verticalLayout.addWidget(self.contentWidget)

        self.retranslateUi(Programmer)
        self.contentWidget.setCurrentIndex(0)
        self.introWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(Programmer.connectProgrammer)
        self.barcodeLineEdit.editingFinished.connect(Programmer.barcodeAbandon)
        self.barcodeLineEdit.returnPressed.connect(Programmer.barcodeScanEnter)
        QtCore.QMetaObject.connectSlotsByName(Programmer)

    def retranslateUi(self, Programmer):
        _translate = QtCore.QCoreApplication.translate
        Programmer.setWindowTitle(_translate("Programmer", "Form"))
        self.indexLabel.setText(_translate("Programmer", "#PROGRAMMER NUMBER#"))
        self.label_2.setText(_translate("Programmer", "PROGRAMÁTOR ODPOJEN"))
        self.pushButton_2.setText(_translate("Programmer", "Pokusit se znovu o spojení"))
        self.introMessageLabel.setText(_translate("Programmer", "Programátor připraven"))
        self.introErrorLabel.setText(_translate("Programmer", "#ERROR#"))
        self.scanBoardLabel.setText(_translate("Programmer", "Naskenujte kód desky:"))
        self.typeLabel.setText(_translate("Programmer", "#TYPE#"))
        self.label_5.setText(_translate("Programmer", "RAM: ??"))
        self.serialNumberLabel.setText(_translate("Programmer", "#SERIAL NUMBER#"))
        self.currentProgress.setFormat(_translate("Programmer", "%p%"))
        self.totalProgress.setFormat(_translate("Programmer", "%v/%m"))

from qrc import icons
